include: package:lint/analysis_options.yaml



linter:
  rules:
    avoid_classes_with_only_static_members: false
    prefer_constructors_over_static_methods: false
    non_constant_identifier_names: false