include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_single_cascade_in_expression_statements: false
    avoid_classes_with_only_static_members: false
    prefer_constructors_over_static_methods: false
    non_constant_identifier_names: false
    sort_pub_dependencies: false
   
